### ISSUE TITLE
Problems with Python 3 (Windows)

### ISSUE THREAD

**Issue by HashtagMC** [mmilidoni/github-downloads-count#12]
When running gdc via `python gdc <user> <repository>` I get the following error:

`File "gdc", line 6`
`print "Usage: `~~`"`~~` + sys.argv[0] + " github-user [github-project]"`.

After I fixed all `print "value"` to `print("value")` it says:
`Traceback (most recent call last):`
`File "gdc", line 16, in (module)`
`import cStringIO`
`ImportError: No module named 'cStringIO'`

**Comment by mmilidoni** [comment]
gdc script is not compatible with python 3. You can try [stonebig fork](https://github.com/stonebig/github-downloads-count).

**Comment by HashtagMC** [comment]
Doesn't work. Using his python3 compatibility effort patch returns nothing (`C:\Python34\python.exe gdc_py_3 hashtagmc`)
