### ISSUE TITLE
IndexError: list assignment index out of range (Python 2.7.10

### ISSUE THREAD

**Issue by HashtagMC** [mmilidoni/github-downloads-count#13]
When using it via `python gdc <user> <repository>` it says:
`Traceback (most recent call last):`
`File "gdc", line 41, in (module)`
`full_names[0] = sys.argv[1] + "/" + sys.argv[1]`
`IndexError: list assignment index out of range`

**Comment by mmilidoni** [comment]
Hi,
what are the command arguments?

**Comment by mmilidoni** [comment]
You have an old release. Please, download latest release that I have just uploaded.

**Comment by HashtagMC** [comment]
Using the latest release (1.2 Beta) via `C:\Python27\python.exe gdc hashtagmc` only gives back downloads for releases, not for pre-releases. Is that intended?

`C:\Python27\python.exe gdc hashtagmc <repository>` results in the same problem as described above:

`Traceback (most recent call last):`
`File "gdc", line 41, in (module)`
`full_names[0] = sys.argv[1] + "/" + sys.argv[1]`
`IndexError: list assignment index out of range`
