### ISSUE TITLE
Download counts for source archives?

### ISSUE THREAD

**Issue by purplehuman** [mmilidoni/github-downloads-count#14]
Hello, I find your script very useful. Thank you very much.
I wonder if it's possible for the script to show also download counts for source archives in the releases.
Thanks.
Edit: I don't know github API. I just wonder if it's possible.

**Comment by HashtagMC** [comment]
Yeah, that would be pretty nice.

**Comment by purplehuman** [comment]
After some searching and reading I see that it's not possible with github API.
Thanks for a very useful script. 
Please close this issue.

**Comment by mmilidoni** [comment]
Tnx
