### ISSUE TITLE
line 41 error

### ISSUE THREAD

**Issue by cryptic0** [mmilidoni/github-downloads-count#16]
./gdc cryptic0 distruct2

Traceback (most recent call last):
  File "./gdc", line 41, in <module>
    full_names[0] = sys.argv[1] + "/" + sys.argv[1]
IndexError: list assignment index out of range

**Comment by anselal** [comment]
I think this issue is resolved.

**Comment by sylvainhalle** [comment]
The issue is *not* resolved if you download the the latest available release (1.2 beta); it still has this problem (using Python 2.7.8 under Cygwin). However, the latest version of the code on the repo is OK. Maybe you could simply create a new release with the current state of the repo?
