### ISSUE TITLE
Any way to get amount of downloads of one file in a repo?

### ISSUE THREAD

**Issue by mitchellkrogza** [mmilidoni/github-downloads-count#20]
Great script, is there any way to get a count of how many times a single file inside a repo is being downloaded? I have a project where I push daily updates and people use my update-script to pull the updated config file on a daily basis. Would be great to be able to get some stats on this to see how many active users are out there.

**Comment by mmilidoni** [comment]
Hello Mitchel, I am sorry but i think it is not possible to count how many times a single file inside a repo is being dowloaded because there is not any Github API service for that.

**Comment by mitchellkrogza** [comment]
Thanks for the reply, think it would be a great feature. I'll log an issue
with Github for a possible feature request for this.
