### ISSUE TITLE
Swapping users causes error

### ISSUE THREAD

**Issue by Randolph42** [mmilidoni/github-downloads-count#5]
./gdc Randolph42
./gdc Alenka
(no result)

# try organisation instead:
./gdc DeepCloudPtyLtd
Traceback (most recent call last):
  File "./gdc", line 48, in <module>
    full_names.insert(0, ensure_str(rep['full_name']))
TypeError: string indices must be integers

**Comment by Jan-E** [comment]
I got the same error with ./gdc rethinkdb (using Python 2.7.9):

    # ./gdc rethinkdb
    Traceback (most recent call last):
      File "./gdc", line 48, in <module>
        full_names.insert(0, ensure_str(rep['full_name']))

Is there a fix?

**Comment by mmilidoni** [comment]
@Randolph42 For Alenka project you have only pre-release, not release. 

@Jan-E ./gdc rethinkdb runs with latest release.
