### ISSUE TITLE
using this script

### ISSUE THREAD

**Issue by ConnieZ** [mmilidoni/github-downloads-count#6]
Hi Michele,

I found your work online, while looking for ways to get download stats from GitHub. I was very excited about it, until I tried to implement this. Forgive me my ignorance, but i was hoping you could explain in a little more detail where to run this script, how to install it. For instance, it's Python script, but I'm not sure if I should run it in Git or Python? Please provide a little more detail on this part.

Thanks for your hard work on this! I hope I get it to work for myself.

Connie

**Comment by mmilidoni** [comment]
Hello Connie,
you can download script with git, and run it on python. See [README.md] (https://github.com/mmilidoni/github-downloads-count/blob/master/README.md)  to run under unix-like platforms, and [this guide] (http://www.pythoncentral.io/execute-python-script-file-shell/) to run it on windows platoform
