### ISSUE TITLE
Script For Windows

### ISSUE THREAD

**Issue by ssirekumar** [mmilidoni/github-downloads-count#7]
Hi 
Can i have same script for windows for knowing GitHub downloads count. If you have any binaries for windows please post me.

Thanks
~ Ssire

**Comment by mmilidoni** [comment]
Hello Ssire,
this is a very simple script, and I don't release it for specific platform. You can run python script under windows, see this guide http://www.pythoncentral.io/execute-python-script-file-shell/

Bye
Michele

**Comment by HashtagMC** [comment]
I finally found this issue after searching for hours. mmilidoni could you add the link you posted to the _readme.md_? That would be very helpful for other people running a Windows OS.

Thanks in advance
HashtagMC
